### ISSUE TITLE
hardhat-gas-reporter conflicts with smockit library

### ISSUE THREAD

**Issue by notsegfault** [cgewecke/hardhat-gas-reporter#57]
When both are specified in hardhat.config.js

```
require('@eth-optimism/smock/build/src/plugins/hardhat-storagelayout');
require("hardhat-gas-reporter");
```

It's impossible to create mocks like this:
```
const MyMock = await ethers.getContractFactory(
  "MyMockContract"
);
const mock = await MyMock.deploy();
await mock.deployed();
```

Error:
```
TypeError: Cannot read property 'from' of undefined
at addGasToAbiMethodsIfNecessary (node_modules/@nomiclabs/hardhat-ethers/src/helpers.ts:313:30)
at getContractFactoryByAbiAndBytecode (node_modules/@nomiclabs/hardhat-ethers/src/helpers.ts:254:27)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

It seems to be related to a conflict in both library ethers versions or BigNumber.

**Comment by cgewecke** [comment]
Thanks for reporting. Suspect it's a bug here, unfortunately 😄 

Will investigate.
